name: pim-gas-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - rdkit
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pyyaml
  - joblib
  - tqdm
  - xgboost
  - pytorch
  - pip:
      - -e .
